os: linux
language: java
jdk: openjdk17

env:
  global:
    - ANDROID_HOME=$HOME/travis-tools/android
    - ANDROID_SDK_ROOT=$HOME/travis-tools/android

before_install:
  - mkdir -p $HOME/travis-tools/android && mkdir $HOME/.android && touch $HOME/.android/repositories.cfg
  - cd $ANDROID_HOME && wget -q "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip" -O commandlinetools.zip
  - unzip -q commandlinetools.zip && cd cmdline-tools
  - mv * tools | mkdir tools && cd $TRAVIS_BUILD_DIR

  - export PATH=$ANDROID_HOME/cmdline-tools/tools/bin/:$PATH
  - export PATH=$ANDROID_HOME/emulator/:$PATH
  - export PATH=$ANDROID_HOME/platform-tools/:$PATH


install:
  # INSTALL REQUIRED ANDROID SDK TOOLS
  - sdkmanager --sdk_root=$ANDROID_HOME --list | awk '/Installed/{flag=1; next} /Available/{flag=0} flag'
  - yes | sdkmanager --sdk_root=$ANDROID_HOME --install "platform-tools" "platforms;android-34" "build-tools;34.0.0" "emulator" "system-images;android-34;google_apis;arm64-v8a"
  - sdkmanager --list --sdk_root=$ANDROID_HOME | awk '/Installed/{flag=1; next} /Available/{flag=0} flag'
  # CREATE AVD
  - echo "no" | avdmanager create avd -n test -k "system-images;android-34;google_apis;arm64-v8a"
  - sudo chmod -R 777 /dev/kvm
  # Start emulator in background and wait for it to start
  - adb kill-server && adb start-server &
  - sleep 15 # sleep values may require adjusting depending on the specific build environment
  - emulator test -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &
