language: android
dist: trusty

jdk:
  - openjdk17

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-34.0.0
    - android-34
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - yes | sdkmanager "platforms;android-34"
  - yes | sdkmanager "build-tools;android-34"