dist: trusty

language: android
jdk: openjdk17
addons:
  apt:
    packages:
      - openjdk-17-jdk

env:
  global:
    - BUILD_API=34
    - BUILD_TOOLS=34.0.0
    - ANDROID_HOME=/usr/local/android-sdk
    - TOOLS=${ANDROID_HOME}/cmdline-tools/latest

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-34.0.0
    - android-34
    - sys-img-armeabi-v7a-android-34
before_script:
  ## Install last version of command line tools
  - wget -q "https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip" -O android-commandline-tools-linux.zip
  - mkdir -p ${ANDROID_HOME}/cmdline-tools
  - unzip -q android-commandline-tools-linux.zip -d ${ANDROID_HOME}/cmdline-tools
  - mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest
  ## Accept licence agreements
  - yes | ${TOOLS}/bin/sdkmanager "platforms;android-34"
  - yes | ${TOOLS}/bin/sdkmanager "build-tools;34.0.0"
  ## Create android 24 AVD and wait until boot is finished
  - echo no | ${TOOLS}/bin/avdmanager create avd -n test -k "system-images;android-34;google_apis;arm64-v8a"ls
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
