os: linux
language: java
jdk: openjdk17

env:
  global:
    - ANDROID_HOME=$HOME/travis-tools/android
    - ANDROID_SDK_ROOT=$HOME/travis-tools/android

before_install:
  - mkdir -p $HOME/travis-tools/android && mkdir $HOME/.android && touch $HOME/.android/repositories.cfg
  - cd $ANDROID_HOME && wget -q "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip" -O commandlinetools.zip
  - unzip -q commandlinetools.zip && cd cmdline-tools
  - mv * tools | mkdir tools && cd $TRAVIS_BUILD_DIR

  - export PATH=$ANDROID_HOME/cmdline-tools/tools/bin/:$PATH
  - export PATH=$ANDROID_HOME/emulator/:$PATH
  - export PATH=$ANDROID_HOME/platform-tools/:$PATH

  # Install KVM
  - sudo apt-get -y --no-install-recommends install bridge-utils libpulse0 libvirt-bin qemu-kvm virtinst ubuntu-vm-builder > /dev/null
  - sudo apt-get install -y libxtst6 libnss3-dev libnspr4 libxss1 libasound2 libatk-bridge2.0-0 libgtk-3-0 libgdk-pixbuf2.0-0 > /dev/null
  - sudo adduser $USER libvirt
  - sudo adduser $USER kvm

install:
  # INSTALL REQUIRED ANDROID SDK TOOLS
  - sdkmanager --sdk_root=$ANDROID_HOME --list | awk '/Installed/{flag=1; next} /Available/{flag=0} flag'
  - yes | sdkmanager --sdk_root=$ANDROID_HOME --install "platform-tools" "platforms;android-34" "build-tools;34.0.0" "emulator" "system-images;android-34;google_apis;x86_64"
  - sdkmanager --list --sdk_root=$ANDROID_HOME | awk '/Installed/{flag=1; next} /Available/{flag=0} flag'
  # CREATE AVD
  - echo "no" | avdmanager create avd -n test -k "system-images;android-34;google_apis;x86_64"
  # Start emulator in background and wait for it to start
  - adb kill-server && adb start-server &
  - sleep 15 # sleep values may require adjusting depending on the specific build environment
  - emulator @test -no-audio -no-window &
  - sleep 60
  - adb shell input keyevent 82 &

script:
  - ./gradlew test
  - ./gradlew connectedAndroidTest