dist: trusty

language: android
addons:
  apt:
    packages:
      - openjdk-17-jdk

env:
  global:
    # Remember to keep these four values in sync with values in the root build.gradle file
    - compileSdkVersion=34
    - minSdkVersion=24
    - targetSdkVersion=34
    - toolsVersion=34.0.0 # default for Android Gradle Plugin 8.2.2
    - JAVA17_HOME=/usr/lib/jvm/java-17-openjdk-amd64

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-34.0.0
    - android-34
before_install:
  - yes | sdkmanager "platforms;android-34"
  - yes | sdkmanager "build-tools;34.0.0"
