language: android
dist: trusty

jdk:
  - openjdk17

env:
  global:
    - ANDROID_API_LEVEL=34
    - EMULATOR_API_LEVEL=24
    - ANDROID_BUILD_TOOLS_VERSION=34.0.0

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-34.0.0
    - android-34
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-34"
  - yes | sdkmanager "build-tools;android-34"